[[plugins]]
repo = 'Shougo/dein.vim'



#--------------------
# 入力支援
#--------------------
# if文などで、endを自動補完
[[plugins]]
repo = 'tpope/vim-endwise'

# カッコを自動補完
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# 非同期で文法チェック
[[plugins]]
repo = 'w0rp/ale'

# 検索時にマッチした個数を表示
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''



#--------------------
# 見た目
#--------------------
# カラーテーマ
[[plugins]]
repo = 'Mofiqul/dracula.nvim'
name = 'dracula'
hook_add = '''
  colorscheme dracula
'''

# defx.nvim関係
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
[[plugins]]
repo = 'kristijanhusak/defx-git'

# Git管理しているファイルで差分を表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
  nnoremap [gitgutter] <Nop>
  nmap <C-h> [gitgutter]
  nmap [gitgutter]j <Plug>GitGutterNextHunk
  nmap [gitgutter]k <Plug>GitGutterPrevHunk
  nmap [gitgutter]u <Plug>GitGutterUndoHunk
'''

# UIをいい感じにする
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-d> [denite]
  nnoremap <silent> [denite]g :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
  nnoremap <silent> [denite]r :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  nnoremap <silent> [denite]p :<C-u>Denite file_rec<CR>
  call denite#custom#option('default', 'prompt', '>')
  call denite#custom#option('_', 'highlight_matched_range', 'None')
  call denite#custom#option('_', 'highlight_matched_char', 'None')
  call denite#custom#map('insert', "<Tab>", '<denite:move_to_next_line>')
  call denite#custom#map('insert', "<S-Tab>", '<denite:move_to_previous_line>')
  call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
  call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
  call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
  call denite#custom#var('grep', 'command', ['pt', '--follow', '--nogroup', '--nocolor', '--hidden'])
  call denite#custom#var('grep', 'default_opts', [])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
'''

# インデントに線を表示する
[[plugins]]
repo = 'Yggdroot/indentLine'

# nerdfontでvimをかっこよくする
[[plugins]]
repo = 'vim-airline/vim-airline'
# hook_add = '''
# source ~/.cache/dein/repos/github.com/vim-airline
# '''
# vim-airlineのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'



#--------------------
# その他
#--------------------
# vimからGitを呼べる
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
'''

# ファイル検索などいろいろ
[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'
depends=['junegunn/fzf']
# hook_add= '''
# source ~/.config/nvim/plugins/fzf-preview.vim
# '''
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
# hook_add = '''
# source ~/.config/nvim/plugins/coc.vim
# '''
